import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author f.bruckmann
 */
public class ConnexionToBDD extends javax.swing.JPanel {

    Connection connexion;

    /**
     * Creates new form ConnexionToBDD
     */
    public ConnexionToBDD() {
        initComponents();
        jTextFieldAdresse.setText("www.cnadal.fr");
        jTextFieldNomBDD.setText("sio2_cv");
        jTextFieldUtilisateurBDD.setText("sio2_cv");
        jTextFieldMDPBDD.setText("formation2020");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConnexion = new javax.swing.JPanel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jLabelAdresse = new javax.swing.JLabel();
        jTextFieldNomBDD = new javax.swing.JTextField();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldMDPBDD = new javax.swing.JTextField();
        jLabelNomBDD = new javax.swing.JLabel();
        jTextFieldUtilisateurBDD = new javax.swing.JTextField();
        jLabelMDPBDD = new javax.swing.JLabel();
        jLabelUtilisateurBDD = new javax.swing.JLabel();
        jLabelEtat = new javax.swing.JLabel();
        jButtonSeConnecter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanelConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelConnexionMouseClicked(evt);
            }
        });

        jTextFieldAdresse.setText("localhost");
        jTextFieldAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdresseActionPerformed(evt);
            }
        });

        jTextFieldPort.setText("3306");
        jTextFieldPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPortActionPerformed(evt);
            }
        });

        jLabelAdresse.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabelAdresse.setText("Adresse du serveur BDD");

        jLabelPort.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabelPort.setText("Port (éventuel)");

        jTextFieldMDPBDD.setText("localhost");
        jTextFieldMDPBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMDPBDDActionPerformed(evt);
            }
        });

        jLabelNomBDD.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabelNomBDD.setText("Nom de la BDD");

        jTextFieldUtilisateurBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUtilisateurBDDActionPerformed(evt);
            }
        });

        jLabelMDPBDD.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabelMDPBDD.setText("Mot de passe BDD");

        jLabelUtilisateurBDD.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabelUtilisateurBDD.setText("Utilisateur BDD");

        jLabelEtat.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabelEtat.setText("                                              Non connecté");

        jButtonSeConnecter.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSeConnecter.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jButtonSeConnecter.setText("Se Connecter");
        jButtonSeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeConnecterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("DAO : Data Access Object with Java");

        javax.swing.GroupLayout jPanelConnexionLayout = new javax.swing.GroupLayout(jPanelConnexion);
        jPanelConnexion.setLayout(jPanelConnexionLayout);
        jPanelConnexionLayout.setHorizontalGroup(
            jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnexionLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelConnexionLayout.createSequentialGroup()
                            .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelConnexionLayout.createSequentialGroup()
                                    .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelAdresse)
                                        .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNomBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelConnexionLayout.createSequentialGroup()
                                    .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelMDPBDD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelUtilisateurBDD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldUtilisateurBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNomBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMDPBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButtonSeConnecter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEtat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConnexionLayout.setVerticalGroup(
            jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnexionLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresse)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPort)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConnexionLayout.createSequentialGroup()
                        .addComponent(jLabelNomBDD)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelMDPBDD))
                    .addGroup(jPanelConnexionLayout.createSequentialGroup()
                        .addComponent(jTextFieldNomBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMDPBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUtilisateurBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUtilisateurBDD))))
                .addGap(27, 27, 27)
                .addComponent(jButtonSeConnecter)
                .addGap(36, 36, 36)
                .addComponent(jLabelEtat)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdresseActionPerformed

    private void jTextFieldUtilisateurBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUtilisateurBDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUtilisateurBDDActionPerformed

    private void jButtonSeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeConnecterActionPerformed
        if (this.connexion == null) { // si la connexion n'est pas active.
            try {
                String ChaineConnexion = "jdbc:mysql://" + jTextFieldAdresse.getText();
                if (!jTextFieldPort.getText().equals("")) {     // s'il existe une information sur le port
                    ChaineConnexion += ":" + jTextFieldPort.getText();
                }
                ChaineConnexion += "/" + jTextFieldNomBDD.getText();

                this.connexion = (Connection) DriverManager.getConnection(ChaineConnexion, jTextFieldUtilisateurBDD.getText(), jTextFieldMDPBDD.getText());
                if (this.connexion != null) {
                    jLabelEtat.setText("La connexion est désormais active.");
                    jButtonSeConnecter.setText("Se déconnecter");
                } else {
                    jLabelEtat.setText("Non connecté");

                }
            } catch (SQLException ex) {
                jLabelEtat.setText("Erreur de connexion, vérifiez les données fournies");
                Logger.getLogger(ConnexionToBDD.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {  //si la connexion est active, on se déconnecte !!!
            jLabelEtat.setText("Non connecté");
            jButtonSeConnecter.setText("Se connecter");
            this.connexion = null;
        }
    }//GEN-LAST:event_jButtonSeConnecterActionPerformed

    private void jPanelConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConnexionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelConnexionMouseClicked

    private void jTextFieldMDPBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMDPBDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMDPBDDActionPerformed

    private void jTextFieldPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSeConnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelEtat;
    private javax.swing.JLabel jLabelMDPBDD;
    private javax.swing.JLabel jLabelNomBDD;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelUtilisateurBDD;
    private javax.swing.JPanel jPanelConnexion;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldMDPBDD;
    private javax.swing.JTextField jTextFieldNomBDD;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldUtilisateurBDD;
    // End of variables declaration//GEN-END:variables
}
